config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :products
  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  validates :name, :price, :brand, presence: true
  validates :price, numericality: { less_than_or_equal_to: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def get_error_messages_from(obj)
    obj.errors.any? ? obj.errors.full_messages : 'Something went wrong.'
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      flash[:notice] = 'Brand was successfully created.'
      redirect_to @brand
    else
      errors = @brand.errors.any? ? @brand.errors.full_messages : 'Something went wrong.'
      flash[:error] = errors
      render :new
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: 'Brand was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /brands/1
  def destroy
    @brand.destroy
    redirect_to brands_url, notice: 'Brand was successfully destroyed.'
  end

  private
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product was successfully created.'
      redirect_to @product
    else
      flash[:error] = get_error_messages_from(@product)
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      flash[:notice] = 'Product was successfully updated.'
      redirect_to @product
    else
      flash[:error] = get_error_messages_from(@product)
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :brand_id, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_CLASSES = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_CLASSES.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def action_for_button(action)
    action == 'edit' ? 'Edit' : 'Add'
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def get_brands
    Brand.all
  end
end

app/views/brands/_form.html.erb
<div class="row">
  <%= form_for(brand, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :name, { class: 'form-control', required: true } %>
    </div>
  </div>

  <div class="from-group">
    <div class="col-sm-3">
      <% action = action_for_button(action_name) %>
      <%= f.submit "#{action} Brand", class: 'btn btn-primary'%>
    </div>
  </div>
  <% end %>
</div>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>
<br>

<%= button_to 'Back', brands_path, method: :get, class: 'btn btn-default' %>

app/views/brands/index.html.erb
<h1>Brands</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Brand', new_brand_path, method: :get, class: 'btn btn-primary', type: 'button' %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<div class="row">
  <%= render 'form', brand: @brand %>
</div>
<br>
<div class="row">
  <div class="col-md-1">
    <%= link_to 'Back', brands_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/brands/show.html.erb
<h2>Brand Information</h2>
<div class="row">
  <div class="col-sm-5">
    <h3>
      Brand No. <%= @brand.id %>: <%= @brand.name %>
      <small><%= link_to 'Edit', edit_brand_path(@brand) %></small>
    </h3>
  </div>
</div>
<br>
<%= button_to 'Back', brands_path, method: :get, class: 'btn btn-default' %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Demo App for Michelada.io</h2>
    <p>
      <strong>About this app:</strong>
    </p>
    <p>
      This app has 2 entities, Brand and Product. A brand can belong to many products and a product has a brand. Below are the requirements.
    </p>
    <h3>Brands</h3>
    <ul>
      <li>User can create a brand. Brands only have a name. Show an error if the user hasn't written a name.</li>
      <li>User can view a list with all the existing brands.</li>
      <li>User can delete a brand. Show an alert asking if the user is sure about doing it.</li>
    </ul>
    <h3>Products</h3>
    <ul>
      <li>User can create a product. Products have: name, brand (select one from the ones already created), description and price.</li>
      <li>Show an error if the product has no name or if the price is greater than 100.</li>
      <li>User can view a list of all existing products. Show the total of the sum of all the products</li>
      <li>User can edit a product.</li>
      <li>User can delete a product.</li>
    </ul>
  </div>
  <h3>Extra points</h3>
  <ul>
    <li>User <a href="getbootstrap.com/">Bootstrap</a> to make the proyect looks nice.</li>
    <li>Create some tests for your code.</li>
  </ul>

  <p>
    The code is hosted in this <a href="https://github.com/Zauvohi/brands-products">repository</a>.
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bp-nav-bar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Brands &amp; Products</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bp-nav-bar">
      <ul class="nav navbar-nav">
        <li><a href="<%= brands_path %>">Brands <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= products_path %>">Products</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductsBrands</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/navbar' %>
      <%= render partial: "shared/flash_notices", flash: flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <%= form_for(product, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :name, { class: 'form-control', required: true } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :brand_id, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.collection_select(
          :brand_id, get_brands, :id, :name,
          {}, { class: 'form-control', required: true }
        )
      %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :price,
        { class: 'form-control', type: 'number', required: true, max: 100 }
      %>
    </div>
  </div>

  <div class="actions">
    <div class="col-sm-3">
      <% action = action_for_button(action_name) %>
      <%= f.submit "#{action} Product", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<br>

<%= button_to 'Back', products_path, method: :get, class: 'btn btn-default' %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% total = 0 %>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% total += product.price %>
    <% end %>
    <tr>
      <td colspan="2"></td>
      <td class="text-center"><strong>Total</strong></td>
      <td colspan="3"><%= total %></td>
    </tr>
  </tbody>
</table>

<br>

<%= button_to 'New Product', new_product_path, method: :get, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<div class="row">
  <%= render 'form', product: @product %>
</div>
<br>
<div class="row">
  <div class="col-md-1">
    <%= link_to 'Back', products_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/products/show.html.erb
<h2>Product Information</h2>
<div class="row">
  <div class="col-sm-12">
    <h4>
      Product No.<%= @product.id %> - <%= @product.name %> (<%= @product.brand.name %>)
      <small><%= link_to 'Edit', edit_product_path(@product) %></small>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-5">
    <h4>Price: $<%= @product.price %></h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-10">
    <h4>Description</h4>
    <p>
      <%= @product.description %>
    </p>
  </div>
</div>
<br>
<%= button_to 'Back', products_path, method: :get, class: 'btn btn-default' %>

app/views/shared/_flash_notices.html.erb
<div class="row">
  <% flash.each do |type, messages| %>
  <div class="<%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">&times;</button>
    <% if messages.respond_to?(:each) %>
    <h4>
      <%= pluralize(messages.count, "error") %> prohibited this brand from being saved:
    </h4>
      <ul>
        <% messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% else %>
        <%= messages %>
    <% end %>
  </div>
  <% end %>
</div>